# Generated by Django 4.2.5 on 2023-11-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='productos/'),
        ),
    ]
