# Generated by Django 4.2.5 on 2023-11-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0007_producto_marca_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(default='sin caracteristicas', max_length=200),
            preserve_default=False,
        ),
    ]
