# Generated by Django 4.2.5 on 2023-11-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0008_producto_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.IntegerField(null=True),
        ),
    ]
