# Generated by Django 4.2.5 on 2023-11-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0011_alter_producto_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='detalles',
            field=models.CharField(max_length=200),
        ),
    ]
