# Generated by Django 4.2.5 on 2023-11-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0012_alter_producto_detalles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
    ]
