# Generated by Django 4.2.5 on 2023-11-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0013_remove_carrito_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(to='e_commerce_app.producto'),
        ),
    ]
